### ISSUE TITLE
Refactor the parsing routine. Communication_BytesReceived()

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/epi-display-samsung-mdc#2]
It looks like the parsing routine is based on collecting and looping through the collection in an somewhat inefficient manner. The protocol gives header and length info that can be used to process only when needed. In the current implementation at 9600 baud it seems to be leaving some info behind. Its probably a good idea to collect the info and process on a new thread as well.

**Comment by jkdevito** [comment]
Closing issue.  The plugin was refactored and merged in PR #18
